/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mystud;

/**
 *
 * @author Denis
 */
public class SecondJFrame extends javax.swing.JFrame {

    /**
     * Creates new form SecondJFrame
     */
    public SecondJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Це моя автобиография. Тут я розповім про своє життя. \nМене звуть Дребезов Денис Олегович.\n Lorem ipsum dolor sit amet, consectetur adipiscing elit. \nDonec in arcu id ligula mollis sollicitudin blandit et nunc. \nCras fringilla dui eu tortor porta laoreet. Suspendisse semper a ligula ut porttitor. \nCurabitur nec commodo nisl. Proin finibus quis risus a aliquet. Quisque facilisis lacinia euismod. Donec luctus libero mi. \nQuisque est dolor, placerat eget vehicula eget, tincidunt ac velit. Maecenas pellentesque eget nulla in volutpat. \nDuis ligula diam, euismod non purus quis, fermentum pretium tellus.\n\nCras eu ante a risus venenatis dapibus. Suspendisse ultrices vulputate vehicula.\n Praesent pretium sagittis pretium. Phasellus rhoncus, nisi in dignissim ultrices, ante ante rhoncus arcu,\n vel fermentum risus erat in neque. Proin nec magna consequat, dignissim libero a, scelerisque sem.\nSed eget odio mi. Donec eu ipsum sit amet ipsum ultricies scelerisque quis et massa. \nCras pulvinar consequat ipsum quis convallis. \nNam vitae leo lectus. Praesent gravida euismod ex sagittis pharetra.\n Donec finibus urna in ultricies lacinia. \nPhasellus tristique, arcu eget commodo rhoncus, diam eros fringilla quam, in tempor neque libero mattis arcu.\n Nunc non iaculis enim. ");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecondJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecondJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecondJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecondJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecondJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
